### PR TITLE
Updated DB diagram and models

### PR DESCRIPTION
**Pull request by FarukOzderim**
DB Design and models are updated according to team's discussions. #215 

-DB Diagram is updated.
-user and affiliation tables are unioned, there is no affiliation table anymore
-university,department,title tables are added,
-project table is updated,
-project_milestones are updated,

Please check the update and consider & revise your DB accesses according to the update.

### CODE REVIEW

**Comment by isiktashamza** [comment]
Degree table should be changed to title table

**Review by EnesToptas — CHANGES_REQUESTED** [review]
User model seems to be deleted, needs to be fixed, also Bio field, a field for short biography of a user should also be added to that model.

**Comment by EnesToptas** [comment]
Also,

google scholar related fields should also be added. those are: h-index, citations, i-index (these 3 also should have since2015 fields), google scholar url

**Comment by FarukOzderim** [comment]
Bio, and citation related fields are added to user table in models and DB design.

**Comment by EnesToptas** [comment]
Thanks, seems great!

**Pull request merged**
