### PR TITLE
Scholar_util endpoints are updated

### PR DESCRIPTION
**Pull request by EnesToptas**
Please review my adaptations to previous api endpoints.
Also merging previous commits of coronavirus team.

### CODE REVIEW

**Comment by UkcaGreen** [comment]
Design of the apis are seems to be changed successfully.
scholarly_util and backend is updated accordingly.
There are few conflicts with the master branch, they should be resolved.

**Comment by EnesToptas** [comment]
> Design of the apis are seems to be changed successfully.
> scholarly_util and backend is updated accordingly.
> There are few conflicts with the master branch, they should be resolved.

Thanks for the review, I will resolve and merge.

**Comment by EnesToptas** [comment]
> i agree with Emilcan, also there are some methods that needs to be updated once again in backend.py and coronavirus_api.py

They can be handled in newer versions I believe, master and this branch were not very different anyway.

**Comment by EnesToptas** [comment]
Although github says that there is a big change. When you actually look there are almost none except the latest commit of mine.

**Pull request merged**
